final Map<String, String> languageMapEnglish = {
  'af': 'Afrikaans',
  'am': 'Amharic',
  'ar': 'Arabic',
  'az': 'Azerbaijani',
  'bg': 'Bulgarian',
  'bn': 'Bengali',
  'bs': 'Bosnian',
  'cs': 'Czech',
  'da': 'Danish',
  'de': 'German',
  'de-AT': 'German (Austria)',
  'de-CH': 'German (Switzerland)',
  'el': 'Greek',
  'en': 'English',
  'en-AU': 'English (Australia)',
  'en-CA': 'English (Canada)',
  'en-GB': 'English (United Kingdom)',
  'en-IN': 'English (India)',
  'en-NZ': 'English (New Zealand)',
  'en-US': 'English (United States)',
  'es': 'Spanish',
  'es-419': 'Spanish (Latin America)',
  'es-ES': 'Spanish (Spain)',
  'et': 'Estonian',
  'fa': 'Persian',
  'fi': 'Finnish',
  'fr': 'French',
  'fr-CA': 'French (Canada)',
  'fr-CH': 'French (Switzerland)',
  'ga': 'Irish',
  'gu': 'Gujarati',
  'he': 'Hebrew',
  'hi': 'Hindi',
  'hr': 'Croatian',
  'hu': 'Hungarian',
  'hy': 'Armenian',
  'id': 'Indonesian',
  'ig': 'Igbo',
  'is': 'Icelandic',
  'it': 'Italian',
  'ja': 'Japanese',
  'ka': 'Georgian',
  'kk': 'Kazakh',
  'km': 'Khmer',
  'kn': 'Kannada',
  'ko': 'Korean',
  'lo': 'Lao',
  'lt': 'Lithuanian',
  'lv': 'Latvian',
  'mk': 'Macedonian',
  'ml': 'Malayalam',
  'mn': 'Mongolian',
  'mr': 'Marathi',
  'ms': 'Malay',
  'mt': 'Maltese',
  'my': 'Burmese',
  'ne': 'Nepali',
  'nl': 'Dutch',
  'no': 'Norwegian',
  'pa': 'Punjabi',
  'pl': 'Polish',
  'pt': 'Portuguese',
  'pt-BR': 'Portuguese (Brazil)',
  'pt-PT': 'Portuguese (Portugal)',
  'ro': 'Romanian',
  'ru': 'Russian',
  'si': 'Sinhala',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'sv': 'Swedish',
  'sw': 'Swahili',
  'ta': 'Tamil',
  'te': 'Telugu',
  'th': 'Thai',
  'tl': 'Tagalog',
  'tr': 'Turkish',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'uz': 'Uzbek',
  'vi': 'Vietnamese',
  'yo': 'Yoruba',
  'zh': 'Chinese',
  'zh-Hans': 'Chinese (Simplified)',
  'zh-Hant': 'Chinese (Traditional)',
  'zu': 'Zulu',
};

final Map<String, String> languageMapAutonyms = {
  'af': 'Afrikaans',
  'am': 'አማርኛ',
  'ar': 'العربية',
  'az': 'Azərbaycanca',
  'bg': 'Български',
  'bn': 'বাংলা',
  'bs': 'Bosanski',
  'cs': 'Čeština',
  'da': 'Dansk',
  'de': 'Deutsch',
  'de-AT': 'Deutsch (Österreich)',
  'de-CH': 'Deutsch (Schweiz)',
  'el': 'Ελληνικά',
  'en': 'English',
  'en-AU': 'English (Australia)',
  'en-CA': 'English (Canada)',
  'en-GB': 'English (United Kingdom)',
  'en-IN': 'English (India)',
  'en-NZ': 'English (New Zealand)',
  'en-US': 'English (United States)',
  'es': 'Español',
  'es-419': 'Español (Latinoamérica)',
  'es-ES': 'Español (España)',
  'et': 'Eesti',
  'fa': 'فارسی',
  'fi': 'Suomi',
  'fr': 'Français',
  'fr-CA': 'Français (Canada)',
  'fr-CH': 'Français (Suisse)',
  'ga': 'Gaeilge',
  'gu': 'ગુજરાતી',
  'he': 'עברית',
  'hi': 'हिन्दी',
  'hr': 'Hrvatski',
  'hu': 'Magyar',
  'hy': 'Հայերեն',
  'id': 'Bahasa Indonesia',
  'ig': 'Asụsụ Igbo',
  'is': 'Íslenska',
  'it': 'Italiano',
  'ja': '日本語',
  'ka': 'ქართული',
  'kk': 'Қазақ тілі',
  'km': 'ភាសាខ្មែរ',
  'kn': 'ಕನ್ನಡ',
  'ko': '한국어',
  'lo': 'ລາວ',
  'lt': 'Lietuvių',
  'lv': 'Latviešu',
  'mk': 'Македонски',
  'ml': 'മലയാളം',
  'mn': 'Монгол',
  'mr': 'मराठी',
  'ms': 'Bahasa Melayu',
  'mt': 'Malti',
  'my': 'မြန်မာစာ',
  'ne': 'नेपाली',
  'nl': 'Nederlands',
  'no': 'Norsk',
  'pa': 'ਪੰਜਾਬੀ',
  'pl': 'Polski',
  'pt': 'Português',
  'pt-BR': 'Português (Brasil)',
  'pt-PT': 'Português (Portugal)',
  'ro': 'Română',
  'ru': 'Русский',
  'si': 'සිංහල',
  'sk': 'Slovenčina',
  'sl': 'Slovenščina',
  'sq': 'Shqip',
  'sr': 'Српски',
  'sv': 'Svenska',
  'sw': 'Kiswahili',
  'ta': 'தமிழ்',
  'te': 'తెలుగు',
  'th': 'ไทย',
  'tl': 'Tagalog',
  'tr': 'Türkçe',
  'uk': 'Українська',
  'ur': 'اردو',
  'uz': 'Oʻzbek',
  'vi': 'Tiếng Việt',
  'yo': 'Yorùbá',
  'zh': '中文',
  'zh-Hans': '中文 (简体)',
  'zh-Hant': '中文 (繁體)',
  'zu': 'IsiZulu',
};
